name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DB_DATABASE: test
  DB_USER: root
  DB_PASSWORD: root

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: test
          POSTGRES_HOST: localhost
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.6

    - name: Install
      run: go get golang.org/x/tools/cmd/goimports

    - name: Test generate
      run: make test-generate

    - name: Test build-lambda
      run: make test-build-lambda

    - name: Test mysql
      run: make test-run-mysql

    - name: Test postgres
      run: make test-run-postgres
